### PR TITLE
Add Travis config file.

### PR DESCRIPTION
**Pull request by arthurschreiber**
@deoxxa Would you be so kind to set up travis on this repo? I'm not setup as a repo owner so I can't do this change myself.

### CODE REVIEW

**Comment by arthurschreiber** [comment]
@deoxxa Ping.

**Comment by deoxxa** [comment]
Sure thing - getting on it now.

**Comment by deoxxa** [comment]
All done, I believe! Let me know if there's anything I missed :)

**Comment by arthurschreiber** [comment]
@deoxxa Sweet stuff, thanks!

**Pull request merged**
